include:
  - local: 'ci-templates/deploy-build.yml'

# ==========================================================
# Terraform VALIDATE for Metabase Module
# ==========================================================
metabase (validate):
  extends: .validate_template
  variables:
    MODULE_NAME: deployments/metabase

# ==========================================================
# Terraform PLAN for Metabase Module
# ==========================================================
metabase (plan):
  extends: .plan_template
  variables:
    MODULE_NAME: deployments/metabase

# ==========================================================
# Terraform APPLY for Metabase Module
# ==========================================================
metabase:
  extends: .apply_template
  parallel:
    matrix:
      - TF_ACTION: [apply, apply-direct, refresh, destroy]
  variables:
    MODULE_NAME: deployments/metabase

    