include:
  - local: 'ci-templates/deploy-build.yml'

# ==========================================================
# Terraform PLAN for Metabase Module
# ==========================================================
metabase_plan:
  extends: .plan_template
  variables:
    MODULE_NAME: "metabase"

# ==========================================================
# Terraform APPLY for Metabase Module
# ==========================================================
metabase_apply:
  extends: .apply_template
  variables:
    MODULE_NAME: "metabase"
  needs:
    - job: metabase_plan
      artifacts: true
    