include:
  - local: 'ci-templates/deploy-build.yml'

# ==========================================================
# Terraform PLAN for Metabase Module
# ==========================================================
metabase (plan):
  extends: .plan_template
  variables:
    MODULE_NAME: metabase

# ==========================================================
# Terraform APPLY for Metabase Module
# ==========================================================
metabase:
  extends: .apply_template
  parallel:
    matrix:
      - TF_ACTION: [apply, refresh, destroy]
  variables:
    MODULE_NAME: metabase

    