include:
  - local: 'ci-templates/deploy-build.yml'

# ==========================================================
# Terraform PLAN for Metabase Module
# ==========================================================
metabase (plan):
  extends: .plan_template
  variables:
    MODULE_NAME: metabase

# ==========================================================
# Terraform APPLY for Metabase Module
# ==========================================================
metabase (apply):
  stage: apply
  extends: .apply_template
  variables:
    TF_ACTION: apply
    MODULE_NAME: metabase
  when: manual

metabase (refresh):
  stage: apply
  extends: .apply_template
  variables:
    TF_ACTION: refresh
    MODULE_NAME: metabase
  when: manual

metabase (destroy):
  stage: apply
  extends: .apply_template
  variables:
    TF_ACTION: destroy
    MODULE_NAME: metabase
  when: manual

    