include:
  - local: 'ci-templates/deploy-build.yml'

# ==========================================================
# Terraform PLAN for RustFS Module
# ==========================================================
rustfs_plan:
  extends: .plan_template
  variables:
    MODULE_NAME: "rustfs"

# ==========================================================
# Terraform APPLY for RustFS Module
# ==========================================================
rustfs_apply:
  extends: .apply_template
  variables:
    MODULE_NAME: "rustfs"