include:
  - local: 'ci-templates/deploy-build.yml'

# ==========================================================
# Terraform VALIDATE for Kafka Module
# ==========================================================
kafka (validate):
  extends: .validate_template
  variables:
    MODULE_NAME: deployments/kafka

# ==========================================================
# Terraform PLAN for Kafka Module
# ==========================================================
kafka (plan):
  extends: .plan_template
  needs: ["kafka (validate)"]
  variables:
    MODULE_NAME: deployments/kafka

# ==========================================================
# Terraform APPLY for Kafka Module
# ==========================================================
kafka:
  extends: .apply_template
  parallel:
    matrix:
      - TF_ACTION: [apply, apply-direct, refresh, destroy]
  variables:
    MODULE_NAME: deployments/kafka