include:
  - local: 'ci-templates/deploy-build.yml'

# ==========================================================
# Terraform VALIDATE for Minio Module
# ==========================================================
minio (validate):
  extends: .validate_template
  variables:
    MODULE_NAME: deployments/minio

# ==========================================================
# Terraform PLAN for Minio Module
# ==========================================================
minio (plan):
  extends: .plan_template
  needs: ["minio (validate)"]
  variables:
    MODULE_NAME: deployments/minio

# ==========================================================
# Terraform APPLY for minio Module
# ==========================================================
minio:
  extends: .apply_template
  parallel:
    matrix:
      - TF_ACTION: [apply, apply-direct, refresh, destroy]
  variables:
    MODULE_NAME: deployments/minio