include:
  - local: 'ci-templates/deploy-build.yml'

# ==========================================================
# Terraform PLAN for Openbao Module
# ==========================================================
openbao (plan):
  extends: .plan_template
  variables:
    MODULE_NAME: openbao

# ==========================================================
# Terraform APPLY for Openbao Module
# ==========================================================
openbao:
  extends: .apply_template
  parallel:
    matrix:
      - TF_ACTION: [apply, apply-direct, refresh, destroy]
  variables:
    MODULE_NAME: openbao
