include:
  - local: 'ci-templates/deploy-build.yml'

# ==========================================================
# Terraform PLAN for Openbao Module
# ==========================================================
openbao (plan):
  extends: .plan_template
  variables:
    MODULE_NAME: openbao

# ==========================================================
# Terraform APPLY for Openbao Module
# ==========================================================
openbao (apply):
  stage: apply
  extends: .apply_template
  variables:
    TF_ACTION: apply
    MODULE_NAME: openbao
  when: manual

openbao (refresh):
  stage: apply
  extends: .apply_template
  variables:
    TF_ACTION: refresh
    MODULE_NAME: openbao
  when: manual

openbao (destroy):
  stage: apply
  extends: .apply_template
  variables:
    TF_ACTION: destroy
    MODULE_NAME: openbao
  when: manual
