# ==========================================================
# Terraform PLAN for Spark Module
# ==========================================================
spark_plan:
  stage: plan
  image: ubuntu:22.04
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
      changes:
        - "spark/main.tf"
      when: always
    - when: never
  script:
    - |
      cat > ${SPARK_MODULE}/backend.hcl <<EOF
      address         = "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${SPARK_MODULE}"
      lock_address    = "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${SPARK_MODULE}/lock"
      unlock_address  = "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${SPARK_MODULE}/lock"
      lock_method     = "POST"
      unlock_method   = "DELETE"
      retry_wait_min  = 5
      username        = "${GITLAB_USERNAME}"
      password        = "${GITLAB_TOKEN}"
      EOF
      echo "✅ Created backend.hcl for module: ${SPARK_MODULE}"

    - ssh -o StrictHostKeyChecking=no root@${TAILSCALE_SERVER} "mkdir -p ${REMOTE_DIR}/${SPARK_MODULE} && mkdir -p ${OUTPUT_DIR}/${SPARK_MODULE}"
    - scp -o StrictHostKeyChecking=no -r ./${SPARK_MODULE} root@${TAILSCALE_SERVER}:${REMOTE_DIR}/
    - echo "✅ Module ${SPARK_MODULE} copied to remote server"

    - ssh -o StrictHostKeyChecking=no root@${TAILSCALE_SERVER} "
        cd ${REMOTE_DIR}/${SPARK_MODULE} &&
        terraform init -upgrade -backend-config=backend.hcl -migrate-state &&
        terraform plan 
      "

    - tailscale logout # Logout to avoid leaking auth key on remote server
  tags:
    - k8s

# ==========================================================
# Terraform APPLY for Spark Module
# ==========================================================
spark_apply:
  stage: apply
  image: ubuntu:22.04
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
      changes:
        - "spark/main.tf"
      when: always
    - when: never
  script:
    - ssh -o StrictHostKeyChecking=no root@${TAILSCALE_SERVER} "
        cd ${REMOTE_DIR}/${SPARK_MODULE} &&
        terraform apply -auto-approve &&
        terraform output -json > ${OUTPUT_DIR}/${SPARK_MODULE}/outputs.json
      "
      
    - tailscale logout # Logout to avoid leaking auth key on remote server
  tags:
    - k8s
    