include:
  - local: 'ci-templates/deploy-build.yml'

# ==========================================================
# Terraform VALIDATE for Superset Module
# ==========================================================
superset (validate):
  extends: .validate_template
  variables:
    MODULE_NAME: deployments/superset

# ==========================================================
# Terraform PLAN for Superset Module
# ==========================================================
superset (plan):
  extends: .plan_template
  variables:
    MODULE_NAME: deployments/superset

# ==========================================================
# Terraform APPLY for Superset Module
# ==========================================================
superset:
  extends: .apply_template
  parallel:
    matrix:
      - TF_ACTION: [apply, apply-direct, refresh, destroy]
  variables:
    MODULE_NAME: deployments/superset
