include:
  - local: 'ci-templates/deploy-build.yml'

# ==========================================================
# Terraform VALIDATE for Database Module
# ==========================================================
database (validate):
  extends: .validate_template
  variables:
    MODULE_NAME: deployments/database

# ==========================================================
# Terraform PLAN for Database Module
# ==========================================================
database (plan):
  extends: .plan_template
  needs: ["database (validate)"]
  variables:
    MODULE_NAME: deployments/database

# ==========================================================
# Terraform APPLY for Database Module
# ==========================================================
database:
  extends: .apply_template
  parallel:
    matrix:
      - TF_ACTION: [apply, refresh, destroy]
  variables:
    MODULE_NAME: deployments/database