include:
  - local: 'ci-templates/deploy-build.yml'

# ==========================================================
# Terraform VALIDATE for Trino Module
# ==========================================================
trino (validate):
  extends: .validate_template
  variables:
    MODULE_NAME: deployments/trino

# ==========================================================
# Terraform PLAN for Trino Module
# ==========================================================
trino (plan):
  extends: .plan_template
  variables:
    MODULE_NAME: deployments/trino

# ==========================================================
# Terraform APPLY for Trino Module
# ==========================================================
trino:
  extends: .apply_template
  parallel:
    matrix:
      - TF_ACTION: [apply, apply-direct, refresh, destroy]
  variables:
    MODULE_NAME: deployments/trino
    