include:
  - local: 'ci-templates/deploy-build.yml'

variables:
  MODULE_NAME: "nessie"

# ==========================================================
# Terraform PLAN for Nessie Module
# ==========================================================
nessie_plan:
  extends: .plan_template

# ==========================================================
# Terraform APPLY for Nessie Module
# ==========================================================
nessie_apply:
  extends: .apply_template
    