include:
  - local: 'ci-templates/deploy-build.yml'

# ==========================================================
# Terraform VALIDATE for Airflow Module
# ==========================================================
airflow (validate):
  extends: .validate_template
  variables:
    MODULE_NAME: deployments/airflow

# ==========================================================
# Terraform PLAN for Airflow Module
# ==========================================================
airflow (plan):
  extends: .plan_template
  needs: ["airflow (validate)"]
  variables:
    MODULE_NAME: deployments/airflow

# ==========================================================
# Terraform APPLY for Airflow Module
# ==========================================================
airflow:
  extends: .apply_template
  parallel:
    matrix:
      - TF_ACTION: [apply, refresh, destroy]
  variables:
    MODULE_NAME: deployments/airflow