include:
  - local: 'ci-templates/deploy-build.yml'

# ==========================================================
# Terraform PLAN for Superset Module
# ==========================================================
superset (plan):
  extends: .plan_template
  variables:
    MODULE_NAME: superset

# ==========================================================
# Terraform APPLY for Superset Module
# ==========================================================
superset (apply):
  stage: apply
  extends: .apply_template
  variables:
    TF_ACTION: apply
    MODULE_NAME: superset
  when: manual

superset (refresh):
  stage: apply
  extends: .apply_template
  variables:
    TF_ACTION: refresh
    MODULE_NAME: superset
  when: manual

superset (destroy):
  stage: apply
  extends: .apply_template
  variables:
    TF_ACTION: destroy
    MODULE_NAME: superset
  when: manual
