include:
  - local: 'ci-templates/deploy-build.yml'

# ==========================================================
# Terraform PLAN for Trino Module
# ==========================================================
trino_plan:
  extends: .plan_template
  variables:
    MODULE_NAME: "trino"

# ==========================================================
# Terraform APPLY for Trino Module
# ==========================================================
trino_apply:
  extends: .apply_template
  variables:
    MODULE_NAME: "trino"
  needs:
    - job: trino_plan
      artifacts: true
    