include:
  - local: 'ci-templates/deploy-build.yml'

# ==========================================================
# Terraform PLAN for Trino Module
# ==========================================================
trino (plan):
  extends: .plan_template
  variables:
    MODULE_NAME: trino

# ==========================================================
# Terraform APPLY for Trino Module
# ==========================================================
trino:
  extends: .apply_template
  parallel:
    matrix:
      - TF_ACTION: [apply, refresh, destroy]
  variables:
    MODULE_NAME: trino
    