include:
  - local: 'ci-templates/deploy-build.yml'

# ==========================================================
# Terraform PLAN for Trino Module
# ==========================================================
trino (plan):
  extends: .plan_template
  variables:
    MODULE_NAME: trino

# ==========================================================
# Terraform APPLY for Trino Module
# ==========================================================
trino (apply):
  stage: apply
  extends: .apply_template
  variables:
    TF_ACTION: apply
    MODULE_NAME: trino
  when: manual

trino (refresh):
  stage: apply
  extends: .apply_template
  variables:
    TF_ACTION: refresh
    MODULE_NAME: trino
  when: manual

trino (destroy):
  stage: apply
  extends: .apply_template
  variables:
    TF_ACTION: destroy
    MODULE_NAME: trino
  when: manual

    