include:
  - local: 'ci-templates/deploy-build.yml'

variables:
  MODULE_NAME: "trino"

# ==========================================================
# Terraform PLAN for Trino Module
# ==========================================================
trino_plan:
  extends: .plan_template

# ==========================================================
# Terraform APPLY for Trino Module
# ==========================================================
trino_apply:
  extends: .apply_template
    