include:
  - local: 'ci-templates/deploy-build.yml'

# ==========================================================
# Terraform PLAN for Minio Module
# ==========================================================
minio (plan):
  extends: .plan_template
  variables:
    MODULE_NAME: minio

# ==========================================================
# Terraform APPLY for minio Module
# ==========================================================
minio (apply):
  stage: apply
  extends: .apply_template
  variables:
    TF_ACTION: apply
    MODULE_NAME: minio
  when: manual

minio (refresh):
  stage: apply
  extends: .apply_template
  variables:
    TF_ACTION: refresh
    MODULE_NAME: minio
  when: manual

minio (destroy):
  stage: apply
  extends: .apply_template
  variables:
    TF_ACTION: destroy
    MODULE_NAME: minio
  when: manual