# ==========================================================
# Terraform PLAN for Minio Module
# ==========================================================
minio_plan:
  stage: plan
  image: ubuntu:22.04
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
      changes:
        - "minio/main.tf"
      when: always
    - when: never
  script:
    - |
      cat > ${MINIO_MODULE}/backend.hcl <<EOF
      address         = "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${MINIO_MODULE}"
      lock_address    = "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${MINIO_MODULE}/lock"
      unlock_address  = "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${MINIO_MODULE}/lock"
      lock_method     = "POST"
      unlock_method   = "DELETE"
      retry_wait_min  = 5
      username        = "${GITLAB_USERNAME}"
      password        = "${GITLAB_TOKEN}"
      EOF
      echo "✅ Created backend.hcl for module: ${MINIO_MODULE}"

    - ssh -o StrictHostKeyChecking=no root@${TAILSCALE_SERVER} "mkdir -p ${REMOTE_DIR}/${MINIO_MODULE} && mkdir -p ${OUTPUT_DIR}/${MINIO_MODULE}"
    - scp -o StrictHostKeyChecking=no -r ./${MINIO_MODULE} root@${TAILSCALE_SERVER}:${REMOTE_DIR}/
    
    - envsubst < .tf.env > .tfvars
    - scp -o StrictHostKeyChecking=no .tfvars root@${TAILSCALE_SERVER}:/opt/.tfvars
    
    - echo "✅ Module ${MINIO_MODULE} copied to remote server"

    - ssh -o StrictHostKeyChecking=no root@${TAILSCALE_SERVER} "
        cd ${REMOTE_DIR}/${MINIO_MODULE} &&
        terraform init -upgrade -backend-config=backend.hcl -migrate-state &&
        terraform plan -var-file=/opt/.tfvars -compact-warnings
      "

    - tailscale logout # Logout to avoid leaking auth key on remote server
  tags:
    - k8s

# ==========================================================
# Terraform APPLY for minio Module
# ==========================================================
minio_apply:
  stage: apply
  image: ubuntu:22.04
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
      changes:
        - "minio/main.tf"
      when: always
    - when: never
  script:
    - ssh -o StrictHostKeyChecking=no root@${TAILSCALE_SERVER} "
        cd ${REMOTE_DIR}/${MINIO_MODULE} &&
        terraform apply -var-file=/opt/.tfvars -auto-approve &&
        terraform output -json > ${OUTPUT_DIR}/${MINIO_MODULE}/outputs.json
      "
      
    - tailscale logout # Logout to avoid leaking auth key on remote server
  tags:
    - k8s
    