include:
  - local: 'ci-templates/deploy-build.yml'

# ==========================================================
# Terraform PLAN for Minio Module
# ==========================================================
minio (plan):
  extends: .plan_template
  variables:
    MODULE_NAME: minio

# ==========================================================
# Terraform APPLY for minio Module
# ==========================================================
minio:
  extends: .apply_template
  parallel:
    matrix:
      - TF_ACTION: [apply, refresh, destroy]
  variables:
    MODULE_NAME: minio