include:
  - local: 'ci-templates/deploy-build.yml'

# ==========================================================
# Terraform PLAN for Kafka Module
# ==========================================================
kafka (plan):
  extends: .plan_template
  variables:
    MODULE_NAME: kafka

# ==========================================================
# Terraform APPLY for Kafka Module
# ==========================================================
kafka:
  extends: .apply_template
  parallel:
    matrix:
      - TF_ACTION: [apply, apply-direct, refresh, destroy]
  variables:
    MODULE_NAME: kafka