include:
  - local: 'ci-templates/deploy-build.yml'

# ==========================================================
# Terraform PLAN for Kafka Module
# ==========================================================
kafka_plan:
  extends: .plan_template
  variables:
    MODULE_NAME: "kafka"

# ==========================================================
# Terraform APPLY for Kafka Module
# ==========================================================
kafka_apply:
  extends: .apply_template
  variables:
    MODULE_NAME: "kafka"
