include:
  - local: 'ci-templates/deploy-build.yml'

# ==========================================================
# Terraform PLAN for Kafka Module
# ==========================================================
kafka (plan):
  extends: .plan_template
  variables:
    MODULE_NAME: kafka

# ==========================================================
# Terraform APPLY for Kafka Module
# ==========================================================
kafka (apply):
  stage: apply
  extends: .apply_template
  variables:
    TF_ACTION: apply
    MODULE_NAME: kafka
  when: manual

kafka (refresh):
  stage: apply
  extends: .apply_template
  variables:
    TF_ACTION: refresh
    MODULE_NAME: kafka
  when: manual

kafka (destroy):
  stage: apply
  extends: .apply_template
  variables:
    TF_ACTION: destroy
    MODULE_NAME: kafka
  when: manual