# ==========================================================
# Terraform PLAN for Kafka Module
# ==========================================================
kafka_plan:
  stage: plan
  image: ubuntu:22.04
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
      changes:
        - "kafka/main.tf"
      when: always
    - when: never
  script:
    - |
      cat > ${KAFKA_MODULE}/backend.hcl <<EOF
      address         = "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${KAFKA_MODULE}"
      lock_address    = "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${KAFKA_MODULE}/lock"
      unlock_address  = "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${KAFKA_MODULE}/lock"
      lock_method     = "POST"
      unlock_method   = "DELETE"
      retry_wait_min  = 5
      username        = "${GITLAB_USERNAME}"
      password        = "${GITLAB_TOKEN}"
      EOF
      echo "✅ Created backend.hcl for module: ${KAFKA_MODULE}"

    - ssh -o StrictHostKeyChecking=no root@${TAILSCALE_SERVER} "mkdir -p ${REMOTE_DIR}/${KAFKA_MODULE} && mkdir -p ${OUTPUT_DIR}/${KAFKA_MODULE}"
    - scp -o StrictHostKeyChecking=no -r ./${KAFKA_MODULE} root@${TAILSCALE_SERVER}:${REMOTE_DIR}/
    - echo "✅ Module ${KAFKA_MODULE} copied to remote server"

    - ssh -o StrictHostKeyChecking=no root@${TAILSCALE_SERVER} "
        cd ${REMOTE_DIR}/${KAFKA_MODULE} &&
        terraform init -upgrade -backend-config=backend.hcl -migrate-state &&
        terraform plan -var="kafka_ui_auth_password=${KAFKA_UI_PASSWORD}"
      "

    - tailscale logout # Logout to avoid leaking auth key on remote server
  tags:
    - k8s

# ==========================================================
# Terraform APPLY for Kafka Module
# ==========================================================
kafka_apply:
  stage: apply
  image: ubuntu:22.04
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
      changes:
        - "kafka/main.tf"
      when: always
    - when: never
  script:
    - ssh -o StrictHostKeyChecking=no root@${TAILSCALE_SERVER} "
        cd ${REMOTE_DIR}/${KAFKA_MODULE} &&
        terraform apply -auto-approve -var="kafka_ui_auth_password=${KAFKA_UI_PASSWORD}"  &&
        terraform output -json > ${OUTPUT_DIR}/${KAFKA_MODULE}/outputs.json
      "
      
    - tailscale logout # Logout to avoid leaking auth key on remote server
  tags:
    - k8s